const test = require('tape')
const hasPrefix = require('../lib/has-prefix')
const stripPrefix = require('../lib/strip-prefix')
const ensureIsRelativeModulePath = require('../lib/ensure-is-relative-module-path')
const getAbsoluteSourceDirname = require('../lib/get-absolute-source-dirname')
const getRelativePathToModule = require('../lib/get-relative-path-to-module')
const getRelativePathToProjectRoot = require('../lib/get-relative-path-to-project-root')
const getLongRelativePathToModule = require('../lib/get-long-relative-path-to-module')
const utils = require('../')

test('hasPrefix', t => {
  t.plan(12)
  const has = path => hasPrefix('~', path)

  t.true(has('~'))
  t.true(has('~/'))
  t.true(has('~/a'))
  t.true(has('~/a/b.js'))

  t.false(has('/'))
  t.false(has('/a'))
  t.false(has('./'))
  t.false(has('./a'))
  t.false(has('a/b.js'))

  t.true(hasPrefix('^', '^/a'))
  t.false(hasPrefix('^', '/a'))
  t.true(hasPrefix('fr!end', 'fr!end/guy'))
})

test('stripPrefix', t => {
  t.plan(9)
  const strip = path => stripPrefix('~', path)
  t.equal(strip('~'), '')
  t.equal(strip('~/'), '')
  t.equal(strip('~/a'), 'a')
  t.equal(strip('~/a/b.js'), 'a/b.js')
  t.equal(strip('a/b'), 'a/b')
  t.equal(strip('/a'), '/a')
  t.equal(stripPrefix('^', '^/a'), 'a')
  t.equal(stripPrefix('fr!end', 'fr!end/'), '')
  t.equal(stripPrefix('fr!end', 'fr!end/guy'), 'guy')
})

test('ensureIsRelativeModulePath', t => {
  t.plan(8)
  const e = ensureIsRelativeModulePath
  t.equal(e(''), './')
  t.equal(e('.file'), './.file')
  t.equal(e('a'), './a')
  t.equal(e('a/b.js'), './a/b.js')
  t.equal(e('./'), './')
  t.equal(e('../'), '../')
  t.equal(e('./a'), './a')
  t.equal(e('../a'), '../a')
})

test('getAbsoluteSourceDirname', t => {
  t.plan(4)
  const g = sourcePath => getAbsoluteSourceDirname('/home/y/project', sourcePath)
  t.equal(g('index.js'), '/home/y/project')
  t.equal(g('a/b.js'), '/home/y/project/a')
  t.equal(g('/project/a/b.js'), '/project/a')
  t.equal(g('/home/y/project/index.js'), '/home/y/project')
})

test('getRelativePathToModule', t => {
  t.plan(12)
  const g = (s, m) => getRelativePathToModule('/home/bro/project', s, m)
  t.equal(g('/home/bro/project/a.js', 'b'), './b')
  t.equal(g('/home/bro/project/a/b/c.js', 'aa'), '../../aa')
  t.equal(g('/home/bro/project/a/b/c.js', 'd/e/f'), '../../d/e/f')
  t.equal(g('a.js', 'b'), './b')
  t.equal(g('a/b/c.js', 'aa'), '../../aa')
  t.equal(g('a/b/c.js', 'd/e/f'), '../../d/e/f')
  t.equal(g('a/b/c.js', 'a/b/cc'), './cc')
  t.equal(g('a/b/c.js', 'a/b'), './')
  t.equal(g('a/b/c.js', 'a/b.js'), '../b.js')
  t.equal(g('a/b/c.js', ''), '../../')
  t.equal(g('a/b/c.js', './'), '../../')
  t.equal(g('a/b/c.js', '../'), '../../../')
})

test('getRelativePathToProjectRoot', t => {
  t.plan(4)
  const g = path => getRelativePathToProjectRoot('/home/bro/project', path)
  t.equal(g('a.js'), './')
  t.equal(g('a/b.js'), '../')
  t.equal(g('/home/bro/project/a.js'), './')
  t.equal(g('/home/bro/project/a/b.js'), '../')
})

test('getLongRelativeModulePath', t => {
  t.plan(12)
  const g = (s, m) => getLongRelativePathToModule('/home/bro/project', s, m)
  t.equal(g('/home/bro/project/a.js', 'b'), './b')
  t.equal(g('/home/bro/project/a/b/c.js', 'aa'), '../../aa')
  t.equal(g('/home/bro/project/a/b/c.js', 'd/e/f'), '../../d/e/f')
  t.equal(g('a.js', 'b'), './b')
  t.equal(g('a/b/c.js', 'aa'), '../../aa')
  t.equal(g('a/b/c.js', 'd/e/f'), '../../d/e/f')
  t.equal(g('a/b/c.js', 'a/b/cc'), '../../a/b/cc')
  t.equal(g('a/b/c.js', 'a/b'), '../../a/b')
  t.equal(g('a/b/c.js', 'a/b.js'), '../../a/b.js')
  t.equal(g('a/b/c.js', ''), '../../')
  t.equal(g('a/b/c.js', './'), '../../')
  t.equal(g('a/b/c.js', '../'), '../../../')
})

test('utils (main module)', t => {
  t.plan(4)
  t.true(utils.hasPrefix('~', '~/a'))
  t.equal(utils.stripPrefix('~', '~/a'), 'a')
  t.equal(utils.getRelativePathToModule('/home/project/bro', 'a.js', 'b'), './b')
  t.equal(utils.getLongRelativePathToModule('/home/project/bro', 'a/b.js', 'c/d'), '../c/d')
})
